### ISSUE TITLE
Default replication factor

### ISSUE THREAD

**Issue by kevin-mcmanus** [LGouellec/kafka-streams-dotnet#291]
Description
===========

According to the [documentation](https://lgouellec.github.io/kafka-streams-dotnet/stream-configuration.html#replicationfactor) the replication factor for a change log topic is 1.

This looks to be correct for `change log` topics but differs from the output of a call to `.To()`, which appears to assume the default value as configured by the broker.

I didn't spot in the documentation an option to change the replication factor for non `change log` topics.

Should there be configuration options for both change logs and standard streams?  My own preference is not to specify the option in code and to fall back to the default of the broker.  Is this currently an option for change log topics?

How to reproduce
================

Not a very useful example but does highlight the question...  Using the latest GA NuGet packages.

```
using Streamiz.Kafka.Net;
using Streamiz.Kafka.Net.SerDes;
using Streamiz.Kafka.Net.Stream;

var config = new StreamConfig<StringSerDes, StringSerDes>();
config.ApplicationId = "test-app";
config.BootstrapServers = "xxx";

StreamBuilder builder = new StreamBuilder();

builder.Stream<string, string>("test-input")
    .GroupByKey()
    .Reduce((x,y) => string.Concat(x,y))
    .ToStream("test-stream")
    .To("test-output");

Topology t = builder.Build();
KafkaStream stream = new KafkaStream(t, config);

Console.CancelKeyPress += (o, e) => {
    stream.Dispose();
};

await stream.StartAsync();
```

* `test-output` has a replication factor of 3 in my environment
* `test-app-KSTREAM-AGGREGATE-STATE-STORE......` has a replication factor of 1

**Comment by LGouellec** [comment]
Hi @kevin-mcmanus , 

Streamiz just create the internal topics before starting the processing, that's why the [replication.factor config](https://lgouellec.github.io/kafka-streams-dotnet/stream-configuration.html#replicationfactor) is only applied for changelog or repartition topic.

Regarding the `.To(..)`, this is not Streamiz which create the topic but directly the broker when the application try to produce the first message inside a none-existing topic
Kafka has a configuration to allow  the c 
https://kafka.apache.org/documentation/#brokerconfigs_auto.create.topics.enable
