### ISSUE TITLE
Examples for state store usage

### ISSUE THREAD

**Issue by explorer14** [LGouellec/kafka-streams-dotnet#72]
Description
===========
Hi,

Kafka Streams noob here, I couldn't find examples of how would I persist messages into and get them back out of the state store, in your [documentation](https://lgouellec.github.io/kafka-streams-dotnet/stores.html#in-memory). Would appreciate some help! 

Essentially I am looking for a C# equivalent of (from Confluent's website):

![image](https://user-images.githubusercontent.com/1242932/115970238-6c198080-a541-11eb-87b7-1a312085b180.png)

Most `Processor` [classes](https://github.com/LGouellec/kafka-streams-dotnet/tree/develop/core/Processors) in your library are internal, so I can't create derivatives like the one shown in the screenshot above, hence my question.

Cheers
Aman

**Comment by LGouellec** [comment]
Hi @explorer14,

It's normal because at time I don't release Processor API in my Kafka streams implementation . 
It's on my todo list for next release maybe 1.3 or 1.4 in few months.

I works since few weeks to persistent state store and it's my first own about next release 1.2 soon I hope. 

Regards,

**Comment by explorer14** [comment]
ah! Had a feeling its probably still in the works! Thanks for the reply!
